version: '3.8'

services:
  db:
    container_name: PollosHermanosDb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: polloshermanosdb
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: